version: '3'

services:
  a2a-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
      - ./plugins:/app/plugins
    command: ["--config", "/app/config/server.json", "--log-level", "debug"]
    environment:
      - TZ=UTC
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/.well-known/agent.json"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Example of running the client as a separate service
  # a2a-client:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   entrypoint: ["/app/bin/a2a-client"]
  #   command: ["--url", "http://a2a-server:8080", "card"]
  #   volumes:
  #     - ./config:/app/config
  #   depends_on:
  #     - a2a-server
